/* eslint import/no-anonymous-default-export: [2, {"allowObject": true}] */
export default {
  // settings
  MINIMUM_PLAYERS: 3,
  MAXIMUM_PLAYERS: 8,
  BASE_POINTS: 50,
  GAME_ID_DICTIONARY: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
  GAME_ID_LENGTH: 4,
  SHORT_ID_DICTIONARY:
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",
  SHORT_ID_LENGTH: 8,
  LOCAL_STORAGE_KEY: "redux",

  // timers
  POLLING_INTERVAL: 3000,
  TUTORIAL_LENGTH: 10000,
  ROUND_INPUT_TIMER: 60000,
  ROUND_VOTE_TIMER: 60000,
  ROUND_SCORE_TIMER: 10000,

  // game states
  ADDING_PLAYERS_PAGE: "addingPlayers",
  TUTORIAL_PAGE: "tutorial",
  ROUND_INPUT_PAGE: "roundInput",
  ROUND_VOTE_PAGE: "roundVote",
  ROUND_SCORE_PAGE: "roundScore",
  FINAL_PAGE: "final",

  // gameplay
  ROUNDS: [
    {
      id: 1,
      title: "Round One",
      scoreMultiplier: 1,
      content: [
       "What is the word for the place where a river starts?",
"What is the quickest way to travel from Hong Kong to Paris?",
"What is the term used for a professional who practices law?",
"When the writer of a book is unknown, what word is used for the author?",
"What is it that you wear on your wrist and that tells you time?",
"What do we call the list of steps that tell you how to put something together?", 
"Who serves food in a restaurant?",
"At what ceremony do students receive their degree or diploma at the end of their period of study?",
"What is the occupation of someone who plays a character in a movie?",
"Name a month that falls between September and November?",
"What is the word for a period of one hundred years?",
"Who reads the news on television?",
"What is the word for a building or room where art exhibitions are held?",
"Which of these was last to be explored, the Himalayas, the moon, or Australia?",
"How many sides are there in a bilateral agreement?",
"What's the name of the annoying sound that people sometimes make when they breathe while sleeping?",
"What object would you use to climb up to the roof of a house?",
"What is the place at home where you cook food?",
"Which short TV program or a part of TV program tell whether it will be sunny or rainy tomorrow?",
"What do we call the meeting where an employer asks a potential employee questions about their work experience?",
"Which animal does wool come from?",
"Which country is in the southern hemisphere. Australia or Canada?",
"What do you call the alphabetical list at the end of a textbook that tells you where to find specific information?",
"Would it be better to go jogging at noon or in the early morning if you want to avoid the hottest part of the day?",
"What do you call a professional trained to treat illnesses?",
"If something such as fabric or medicine is artificially made, not natural, what do we say it is?",
"At what age does someone become a teenager?",
"What do we call a company or organization that gives money to a sports or arts event in exchange for advertising?",
"What’s the color of the medal that a champion gets?",
"What desk should you go to when you first arrive to stay at a hotel?",
"Ice sports are likely to feature in which Olympics - Summer or Winter?",
"Which major branch of science deals with classification of living things?",
"What is the common term for websites such as Facebook and Twitter?",
"What is the job title of someone who designs buildings?",
"What is the source of solar energy?",
"What does the main difference between a wristwatch and clock relate to?",
"What features do pianos and computers have in common?",
"To improve their health and fitness,most people either try to improve their diet or...?",
"If you are feeling 'fed up'; is it a positive or negative feeling?",
"What do we call a period of ten years?",
"What do you call a specialist who repairs leaking water pipes?",
"If someone lives in an urban area, where do they live?",
"Where would you keep the meat you wish to keep frozen at home?",
"A lack of which kind of weather causes drought, dry weather or rainy weathe?",
"What do we call the piece of paper that proves you have bought an item?",
"Where would you go to work out on a treadmill?",
"Where would you go to see exhibits of dinosaurs?",
"What is 3 quarters of 100%?",
"Where do you pay for your purchases at a supermarket?",
"What term is used for the amount of money you pay a landlord for living in their house or apartment?",
      ],
    },
    {
      id: 2,
      title: "Final Round",
      scoreMultiplier: 2,
      content: [
        "The most expensive software ever imagined.",
        "The most awkward moment in earth's history.",
        "No. NO. NO! I will not let _____ ruin my day.",
        "The real reason that Elon Musk started SpaceX.",
        "The one thing that will prevent us from reaching 2021.",
        "The title of a movie that everyone secretly loves, but will never admit to.",
        "The end of the Silicon Valley will come from _____.",
        "The most annoying thing about Twitter.",
      ],
    },
  ],
};
